# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
csv_path = "../WeatherPy/citydf.csv"

# Import the books.csv file as a DataFrame
weather_df = pd.read_csv(csv_path, encoding="utf-8")
weather_df.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,carnarvon,-25.627169,108.757421,69.80,83,1,4.63,AU,1619194190
1,illoqqortoormiut,86.088628,-29.659653,15.62,91,100,4.17,RU,1619194190
2,cherskiy,75.813948,163.464228,68.00,60,0,4.63,ZA,1619193686
3,cape town,-70.592852,-14.523802,42.80,87,75,1.01,AR,1619194067
4,ushuaia,-84.071563,-38.650959,57.20,82,75,10.80,PT,1619194191

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# Configure gmaps
gmaps.configure(api_key=g_key)

In [4]:

weather_df.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,carnarvon,-25.627169,108.757421,69.80,83,1,4.63,AU,1619194190
1,illoqqortoormiut,86.088628,-29.659653,15.62,91,100,4.17,RU,1619194190
2,cherskiy,75.813948,163.464228,68.00,60,0,4.63,ZA,1619193686
3,cape town,-70.592852,-14.523802,42.80,87,75,1.01,AR,1619194067
4,ushuaia,-84.071563,-38.650959,57.20,82,75,10.80,PT,1619194191

In [5]:
locations = weather_df[["Lat", "Lng"]]

In [6]:
weight  = weather_df["Humidity"].astype(float)

In [7]:
figW = gmaps.figure()

# Create heat layer
heat_layerW = gmaps.heatmap_layer(locations, weights=weight, 
                                 dissipating=False, max_intensity=10,
                                 point_radius=1)


# Add layer
figW.add_layer(heat_layerW)

# Display figure
figW

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [8]:
#  * A max temperature lower than 90 degrees but higher than 70.

#   * Wind speed less than 20 mph.

#   * less than 30 cloudiness.

In [14]:
Weather_Criteria = weather_df[(weather_df["Max Temp"]>70)&(weather_df["Max Temp"]<90)& (weather_df["Wind Speed"]<20)& (weather_df["Cloudiness"]<10)]
WC= Weather_Criteria.dropna()
WC

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
40,qaanaaq,84.103527,-37.270616,76.10,82,5,2.07,ID,1619194200
51,ghazipur,-74.771828,36.200520,75.99,43,1,3.23,US,1619193576
54,plettenberg bay,78.987562,62.403537,78.80,78,0,1.00,CN,1619194206
58,nanning,-42.524076,-159.266808,78.80,69,0,11.32,BR,1619194207
62,arraial do cabo,13.674135,-142.699388,70.12,47,3,0.58,BR,1619194208
89,los llanos de aridane,89.032145,-128.519933,71.60,30,0,4.63,FR,1619194216
92,sestri levante,-12.471965,-0.528003,72.00,68,1,2.68,ZA,1619194217
101,hambantota,62.401218,-78.634975,74.35,40,0,3.23,MX,1619194219
122,hithadhoo,-42.849953,-138.869140,71.60,68,0,3.60,PE,1619194225
170,nueve de julio,-10.888923,-20.777767,75.20,28,0,3.09,IT,1619194239
173,askino,-33.002252,-49.093742,72.00,46,0,3.09,GR,1619194239
175,nome,-14.253127,-56.222730,72.00,30,2,6.25,IL,1619194240
187,port hedland,20.998530,110.766843,78.51,41,1,2.84,AU,1619194243
188,lardos,-30.542032,118.691101,73.71,69,9,5.44,CV,1619194244
197,hermanus,-42.507104,-63.664676,82.40,61,1,2.06,MX,1619194246
204,sao filipe,-87.622971,155.557921,81.48,78,2,1.73,LK,1619194051
219,altay,-54.818334,-45.197855,71.24,46,0,2.24,PK,1619194173
234,arkhangelos,-26.475583,-79.475972,73.69,22,0,1.01,BW,1619194257
246,kyzyl-suu,-36.439606,-61.529957,84.20,48,0,4.12,BR,1619194260
256,muisne,-31.482192,-75.101094,71.60,68,0,9.77,MR,1619194263
257,sibolga,-20.762276,8.095056,84.20,48,0,2.41,BR,1619194263
263,mbuji-mayi,-33.962231,-9.240249,75.38,18,0,2.06,MX,1619193995
267,grindavik,-66.298513,-83.926135,73.40,73,1,2.06,US,1619194266
274,hutchinson,-39.598577,107.678038,75.76,41,1,2.22,IN,1619194268
296,antofagasta,-14.173684,-144.549931,79.02,84,0,5.69,CN,1619194275
333,gazli,-13.967849,-6.592985,82.40,55,1,3.67,JM,1619194286
342,muyezerskiy,16.598640,36.600306,80.01,81,5,0.45,HK,1619194215
380,whitehorse,82.187291,-111.791125,87.80,48,0,3.60,AE,1619194299
382,sarangani,29.566973,123.612955,82.76,65,9,1.54,HT,1619194300
398,matagami,46.430570,-39.754955,84.54,60,2,2.67,CU,1619194304
415,eyl,30.959967,-171.016200,76.10,67,3,8.45,BS,1619194309
416,geraldton,-81.670248,-173.232367,80.60,57,0,8.23,PE,1619194310
417,noumea,76.367312,32.115745,86.94,43,1,1.52,BR,1619194310
455,dunmore town,53.443531,147.787100,78.80,7,0,4.12,IR,1619194322
467,tazovskiy,42.746407,-60.259294,83.73,64,6,5.91,HN,1619194325
485,dunedin,45.919317,-7.726154,80.60,57,0,8.23,PE,1619194331
494,mujiayingzi,-31.987953,-25.534538,77.00,57,0,3.60,AR,1619194130
495,isilkul,45.799190,109.564690,75.47,22,1,2.30,SY,1619194333
498,luganville,-50.446605,-11.731081,89.85,39,2,1.91,CU,1619194334
501,trairi,-19.800015,-84.000519,74.70,46,1,2.00,BR,1619194335
509,acarau,14.672800,65.375841,77.00,44,0,2.57,BR,1619194338
510,ekhabi,-85.100650,-24.561213,89.60,18,0,6.17,EG,1619194338
511,abaza,64.015877,166.748438,82.83,71,1,4.93,PK,1619194338
529,sao francisco,-23.543653,-78.921685,84.24,69,1,3.45,IN,1619194344
531,esperance,10.037006,-163.967646,80.60,50,0,5.14,BR,1619194344
555,buraydah,41.710982,80.590149,75.00,76,6,4.24,AU,1619194351

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [15]:
import requests
import json

In [18]:
target_coordinates = WC[['Lat','Lng']]
target_search = "Hotel"
target_radius = 5000
target_type = "Hotel"

# set up a parameters dictionary
params = {
    "location": target_coordinates,
    "keyword": target_search,
    "radius": target_radius,
    "rankby": "distance",
    "type": target_type,
    "key": g_key
}

# base url
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

# run a request using our params dictionary
response = requests.get(base_url, params=params).json()
response
for index, row in response:

    # get restaurant type from df
    Hotel_type = row['Hotel']

    # add keyword to params dict
    params['keyword'] = target_search

    # assemble url and make API request
    
    # extract results
    results = response['results']
    
    try:
        print(f"Closest {Hotel_type} Hotel is {results[0]['name']}.")
        
        types_df.loc[index, 'name'] = results[0]['name']
        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        
    print("------------")

{'html_attributions': [], 'results': [], 'status': 'INVALID_REQUEST'}

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure